### ISSUE TITLE
Unable to initalise bootstrap-multiselect in npm

### ISSUE THREAD

**Issue by KeironO** [davidstutz/bootstrap-multiselect#584]
Hi there,

I'm having issues on intalising the bootstrap-multiselect module in my web application. I am getting the following 'stacktrace'.

```bash

react-bootstrap-multiselect/lib/bootstrap-dropdown.js:136
  var old = $.fn.dropdown
                ^
TypeError: Cannot read property 'dropdown' of undefined
    at /react-bootstrap-multiselect/lib/bootstrap-dropdown.js:136:17
    at Object.exports.init (/react-bootstrap-multiselect/lib/bootstrap-dropdown.js:162:2)
    at Object.<anonymous> (/react-bootstrap-multiselect/lib/index.js:5:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/react-bootstrap-multiselect/demo/src/App.js:5:19)
```

**Comment by davidstutz** [comment]
Looks like some dependencies are missing, but I can't really help you without more information.
