### ISSUE TITLE
Unable to initalise bootstrap-multiselect in npm

### ISSUE THREAD

**Issue by MiguelAngelRG** [davidstutz/bootstrap-multiselect#585]
Hi there,

I'm having issues on intalising the bootstrap-multiselect module in my web application. I am getting the following 'stacktrace'.

bootstrap-multiselect.js:1416
}(window.jQuery);
  ^
ReferenceError: window is not defined
    at Object.<anonymous> (bootstrap-multiselect.js:1416:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (app.js:14:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by davidstutz** [comment]
Related: #584.

**Comment by thadclay** [comment]
I was able to get it working this way

```javascript
var $ = require('jquery');
var multiselect = require('bootstrap-multiselect');
$.multiselect = multiselect;

$("#example").multiselect(multiOptions)
```

**Comment by davidstutz** [comment]
Will add this to the FAQ.

**Comment by UseMuse** [comment]
Can't resolve 'knockout' in '...node_modules\bootstrap-multiselect\dist\js'	not found

**Comment by melbazany** [comment]
Seconding @UseMuse. Anyone else have a solution? Potentially using 'import' syntax?

**Comment by danse-nr3** [comment]
Solution by @thadclay does not work, `require` fails. https://github.com/davidstutz/bootstrap-multiselect/pull/1278 enables assigning `jQuery` to `globalThis` so that bootstrap-multiselect can find it defined
